# Generated by Django 5.0.6 on 2025-05-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_city_country_dataentry_pestle_region_sector_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('insight', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.CharField(blank=True, max_length=10, null=True)),
                ('impact', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.CharField(blank=True, max_length=100, null=True)),
                ('published', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='pestle',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='region',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='swot',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='topic',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Pestle',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Swot',
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
