# Generated by Django 5.0.6 on 2025-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_insight_added_alter_insight_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
